#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Submit every URL to IndexNow (Bing, Yandex, Seznam, Naver).

Usage:   python3 _generator/indexnow.py            # verify the key is live, then submit
         python3 _generator/indexnow.py --dry-run  # print the payload, send nothing

WHY THIS EXISTS
Google is not an IndexNow participant, so this does NOT replace Search Console — it is the
one indexing lever available without a search-engine account, and it covers Bing (which also
feeds Copilot/ChatGPT search) plus Yandex, Seznam and Naver. It is also useful later: every
growth cycle adds pages, and a ping tells those engines about them immediately instead of
waiting for a recrawl.

Ownership is proven by serving https://<host>/<key>.txt — generated by build.py — so this
script checks that file is actually LIVE before submitting. Submitting with an unreachable
key file just returns 403 and teaches you nothing.
"""
import json
import os
import sys
import urllib.error
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build import SITE_URL, TOOLS, INDEXNOW_KEY, slug_path

ENDPOINT = "https://api.indexnow.org/indexnow"
KEY_URL = SITE_URL + "/" + INDEXNOW_KEY + ".txt"

# This machine routes outbound traffic through a proxy that 403s Python's default User-Agent.
# Without a browser UA every request here fails, and the failure looks like IndexNow rejecting
# the submission. See PROGRESS.md, "Environment bugs found only by testing the live site".
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36")


def opener():
    op = urllib.request.build_opener()
    op.addheaders = [("User-Agent", UA)]
    return op


def urls():
    out = [SITE_URL + "/"]
    for t in TOOLS:
        out.append(SITE_URL + slug_path(t))
    out += [SITE_URL + "/about", SITE_URL + "/privacy"]
    return out


def get(url):
    try:
        with opener().open(url, timeout=20) as r:
            return r.status, r.read().decode("utf-8", "replace").strip()
    except urllib.error.HTTPError as e:
        return e.code, ""
    except Exception as e:
        return None, str(e)


def main():
    dry = "--dry-run" in sys.argv
    site = urls()

    print("IndexNow submission")
    print("  host      : %s" % SITE_URL)
    print("  key file  : %s" % KEY_URL)
    print("  urls      : %d" % len(site))
    print()

    status, body = get(KEY_URL)
    if status != 200 or body != INDEXNOW_KEY:
        print("ABORT — the key file is not live yet.")
        print("  expected status 200 and body %r" % INDEXNOW_KEY)
        print("  got status %s and body %r" % (status, body[:60]))
        print("  Fix: rebuild, redeploy, then run this again.")
        return 1
    print("  key file live and correct ✓")
    print()

    payload = {
        "host": SITE_URL.replace("https://", "").replace("http://", ""),
        "key": INDEXNOW_KEY,
        "keyLocation": KEY_URL,
        "urlList": site,
    }

    if dry:
        print("--dry-run, sending nothing. Payload:")
        print(json.dumps(payload, indent=2)[:1200])
        return 0

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        ENDPOINT, data=data,
        headers={"Content-Type": "application/json; charset=utf-8",
                 "User-Agent": UA},
        method="POST")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            code, txt = r.status, r.read().decode("utf-8", "replace").strip()
    except urllib.error.HTTPError as e:
        code, txt = e.code, (e.read().decode("utf-8", "replace").strip() if e.fp else "")
    except Exception as e:
        print("FAILED to reach IndexNow: %s" % e)
        return 1

    # 200 = accepted, 202 = accepted but key pending validation. Both are success.
    ok = code in (200, 202)
    print("  HTTP %s %s" % (code, "— accepted ✓" if ok else "— rejected ✗"))
    if txt:
        print("  response: %s" % txt[:300])
    if not ok:
        print()
        print("  200 = accepted | 202 = accepted, key pending | 403 = key file not reachable")
        print("  422 = URLs do not belong to the host | 429 = too many requests, slow down")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
